# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 501, 481))
        self.groupBox.setObjectName("groupBox")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(139, 50, 341, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.label_date = QtWidgets.QLabel(self.groupBox)
        self.label_date.setGeometry(QtCore.QRect(40, 60, 67, 17))
        self.label_date.setObjectName("label_date")
        self.label_time = QtWidgets.QLabel(self.groupBox)
        self.label_time.setGeometry(QtCore.QRect(40, 120, 67, 17))
        self.label_time.setObjectName("label_time")
        self.label_location = QtWidgets.QLabel(self.groupBox)
        self.label_location.setGeometry(QtCore.QRect(40, 170, 67, 17))
        self.label_location.setObjectName("label_location")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setGeometry(QtCore.QRect(137, 120, 341, 26))
        self.timeEdit.setObjectName("timeEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(142, 170, 331, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(43, 240, 431, 211))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.label_time.setText(_translate("MainWindow", "Time"))
        self.label_location.setText(_translate("MainWindow", "Location"))



window = QWidget()
window.setWindowTitle('Appointment details')
window.setGeometry(100, 100, 500, 500)

window.show()
sys.exit(app.exec_())